title =                      "XPS 730x"
languageCode =               "en-us"

# hostname (and path) to the root eg. http://spf13.com/
baseurl =                    "http://730x.org/" 
canonifyUrls =               true

# include content marked as draft
buildDrafts =                true 

# Do not build RSS files
disableRSS =                 true  

footnoteAnchorPrefix =       ""
footnoteReturnLinkContents = ""

# edit new content with this editor, if provided
editor =                     ""
newContentEditor =           ""

paginate =                   10
paginatePath =               "page"
#permalinks =                 ""

[blackfriday]
	plainIdAnchors = true
	extensions = ["HTML_NOFOLLOW_LINKS", "EXTENSION_STRIKETHROUGH"]

[permalinks]
	article = "/:title/"
	file = "/file/:filename/"
	image = "/file/:filename/"

[[menu.sitenav]]
identifier = "h2c"
menu = "h2c"
pre = "H<sub>"
name = "2"
post = "</sub>C Cooling System"
url = "/h2c/"
weight = -100
[[menu.sitenav]]
	parent = "h2c"
	name = "Overview"
	url = "/h2c/"
	weight = -500
[[menu.sitenav]]
	parent = "h2c"
	name = "Wiring & Pin-outs"
	url = "/h2c-wiring/"
	weight = -400
[[menu.sitenav]]
	parent = "h2c"
	name = "TEC Cooling System"
	url = "/h2c-tec/"
	weight = -300
[[menu.sitenav]]
	parent = "h2c"
	name = "Repairing the H2C"
	url = "/h2c-repairing/"
	weight = -200
[[menu.sitenav]]
	parent = "h2c"
	name = "Modifying the H2C"
	url = "/h2c-mods/"
	weight = -100
[[menu.sitenav]]
identifier = "mobo"
menu = "mobo"
name = "Motherboard"
url = "/mobo/"
weight = -90
[[menu.sitenav]]
	parent = "mobo"
	name = "Overview "
	url = "/mobo/"
	weight = -400
[[menu.sitenav]]
	parent = "mobo"
	name = "Upgrading Motherboard"
	url = "/upgrading-motherboard/"
	weight = -300	
[[menu.sitenav]]
	parent = "mobo"
	name = "BIOS"
	url = "/bios/"
	weight = -200
[[menu.sitenav]]
	parent = "mobo"
	name = "Motherboard Wiring"
	url = "/motherboard-wiring/"
	weight = -100
[[menu.sitenav]]
identifier = "support"
menu = "support"
name = "Support"
url = "/support/"
weight = -10
